### ISSUE TITLE
要不要包成小書籤 (bookmarklet) ？

### ISSUE THREAD

**Issue by GHolk** [wabilin/MumiGiveP#19]
也就是 `javascript:alert('hey')` 開頭的 url 。
感覺會比較方便，不用為了發錢另外裝一個外掛。
我可以幫忙包，但我看不懂 flow ……。

另外希望可以讓使用者直接輸入 id 名單來發。
昨天在 firefox 上跑好像有點問題？
但不記得了， [自己又寫了一個用 tmux 發的][tmux give p] 。

[tmux give p]: http://github.com/GHolk/loco/blob/master/bin/tmux-give-p.sh

**Comment by wabilin** [comment]
我自己沒碰過 bookmarklet 有辦法用 bookmarklet 就做到目前和未來規劃的功能嗎?
目前計畫下一步是會記住密碼和發錢數量等等的設定 webextension 我確定是能做的

flow 基本上把型別宣告 (`: xxx`) 肉眼拿掉就是一般的 JavaScript

FireFox 上我目前是測不出問題 如果有重現什麼問題的話歡迎再反應

用 tmux 做這個功能 感覺想法不錯XD

**Comment by GHolk** [comment]
tmux 就比 expect 還原始，只能 capture-pane 看整個視窗的內容。

bookmarklet 可以想像成把 *F12 打開 web console 貼上一段 javascript 執行* ，
這整個流程包成一個書籤，只要按下去就在現在這個頁面執行書籤中的 js 。
所以基本是沒辦法存資料。
（除非你把密碼存在 localstorage cache ，
或發 ajax 到遠端的 server 。）

小書籤好處是只要加到書籤就能直接用，不用安裝。
壞處是比較少人知道怎麼用，很古老的東西了。

**Comment by wabilin** [comment]
考量使用情境 目前沒這個打算，先close了喔
