### ISSUE TITLE
Mac 無法抓取到ID

### ISSUE THREAD

**Issue by hunter123321000** [wabilin/MumiGiveP#26]
mac 10.14.4
chrome 76.0.3809.132
發幣時無法抓取到文章推文的ID...

**Comment by wabilin** [comment]
方便提供文章連結嗎？

**Comment by hunter123321000** [comment]
#1T2lAtia

從我的iPhone傳送

**Comment by wabilin** [comment]
I would check it this weekend

**Comment by wabilin** [comment]
@hunter123321000 >
抱歉現在才處理，沒有看板名稱只有代碼找不到文章
能麻煩再給一下看板 或是網頁版連結嗎

感謝
